services:
  app:
    build: .
    container_name: travel-plan
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/travelPlan
      - JWT_SECRET=hackathon_project
      - NODE_ENV=development
      - PORT=2100
    ports:
      - "2100:2100"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: travelPlan-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travelPlan
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
